name: CI workflow


on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Just-echo-1:
    runs-on: ubuntu-latest
    steps:
      - name: First action 1
        run: |
          echo "first action 1" 

  Just-echo-2:
      needs: Just-echo-1  #  This makes Just-echo-2 depend on Just-echo
      runs-on: ubuntu-latest
      steps:
        - name: First action 2
          run: |
            echo "first action 2" 
  
  Just-echo-3:
      needs: Just-echo-2 # This makes Just-echo-3 depend on Just-echo-2
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: 22.13.0
          - name: First action 3
            run: |
              npm init
              npm test
              
